# Generated by Django 4.1 on 2022-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
